Use << instead of += since = isn't defined for ActiveModel::Errors
NoMethodError (undefined method `[]=' for #<ActiveModel::Errors:0x000055b310fcd780>)